### ISSUE TITLE
Inserir estrutura de try/except para cada importação e seção do MT

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#112]
Inserir estrutura de try/cacth para cada importação e seção do MT

**Comment by ddss** [comment]
Acredito que o try/except seria útil na seção de importação do MT e MT_Linear.

Entretanto, não sou a favor de try/except sistemáticas "nas seções" do motor de cálculo, pois, em teoria, a validação deveria evitar problemas.
