### ISSUE TITLE
Escala dos gráficos em notação científica.

### ISSUE THREAD

**Issue by HarrisonHenri** [ddss/MT_PEU#121]
Colocar a escala em notação científica.
![calculado_fl0_y_funcao_x1_sem_incerteza](https://cloud.githubusercontent.com/assets/13942973/12565503/6a7d3ffe-c393-11e5-8147-6989d1a8195e.png)

**Comment by ddss** [comment]
@HarrisonHenri , favor incluir os dados para que eu posa reproduzir o gráfico.

**Comment by HarrisonHenri** [comment]
Seguem dados.

[ux.txt](https://github.com/ddss/MT_PEU/files/148874/ux.txt)
[uy.txt](https://github.com/ddss/MT_PEU/files/148875/uy.txt)

**Comment by HarrisonHenri** [comment]
Segue o resto dos dados.
[Exemplo.txt](https://github.com/ddss/MT_PEU/files/148877/Exemplo.txt)
[relatorio-parametros.txt](https://github.com/ddss/MT_PEU/files/148881/relatorio-parametros.txt)
[relatorio-predicao.txt](https://github.com/ddss/MT_PEU/files/148879/relatorio-predicao.txt)
[ux.txt](https://github.com/ddss/MT_PEU/files/148882/ux.txt)
[uy.txt](https://github.com/ddss/MT_PEU/files/148878/uy.txt)
[y-calculado-predicao.txt](https://github.com/ddss/MT_PEU/files/148880/y-calculado-predicao.txt)

**Comment by ddss** [comment]
Provavelmente o commit d414556d0293b495d4348a78dfee9095854214b7 resolve o problema

**Comment by ddss** [comment]
Para fechamento dessa issue, falta validação com o seu estudo de caso @HarrisonHenri

**Comment by HarrisonHenri** [comment]
Você que vai validar Daniel?

**Comment by ddss** [comment]
@HarrisonHenri , você poderia validar.

Obs.: se quiser validar, baixe uma nova versão do branch Teste, e a versão v0.3-beta do PSO.

**Comment by ddss** [comment]
Validado com os dados do seu projeto.
