### ISSUE TITLE
Gráfico de y experimental vs y calculado (representação de reta)

### ISSUE THREAD

**Issue by HarrisonHenri** [ddss/MT_PEU#122]
1° bissetriz deve tomar o gráfico todo.
![grafico_fl0_yexp_vs_ycalc_com_var](https://cloud.githubusercontent.com/assets/13942973/12565548/b33549c6-c393-11e5-8ec7-b3305c07b6f5.png)
![grafico_fl0_yexp_vs_ycalc_sem_var](https://cloud.githubusercontent.com/assets/13942973/12565556/b9b5c488-c393-11e5-9017-499a3f3825b0.png)

**Comment by ddss** [comment]
Deve vir associada à correção da issue #120

**Comment by ddss** [comment]
Provavelmente, o commit d414556d0293b495d4348a78dfee9095854214b7 resolve este problema.
