### ISSUE TITLE
Erro com nome do projeto utilizando caracteres especiais.

### ISSUE THREAD

**Issue by HarrisonHenri** [ddss/MT_PEU#125]
O program não executa quando o nome do projeto tem caracteres especiais.
![nova imagem](https://cloud.githubusercontent.com/assets/13942973/14189639/be4c10f6-f764-11e5-8c1c-2adc8b37e38d.png)

**Comment by ddss** [comment]
Validação que impede que o nome do Projeto tenha caracteres especiais existe. Tentarei reproduzir o erro e vou verificar o que ocorreu.

**Comment by HarrisonHenri** [comment]
Talvez o erro só venha a ocorrer quando da utilização de caracteres especiais com espaços.

**Comment by ddss** [comment]
Relacionado à issue #7 

Possível solução: S.isalnum() -> bool (Assuma que S é um string)
