### ISSUE TITLE
flag gráficos

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#13]
Avaliar a possibilidade de transformar os tipos de gráficos solicitados em flags.

**Comment by ddss** [comment]
flags são estruturas que indicam alguma característica marcante, exemplo: a presença de dados de validação altera o comportamento do cállculo da matriz de covariância da predição.

No caso, os tipos de gráfiicos atuam como switches e não são aplicáveis para toda a classe.

Proposta rejeitada.
