### ISSUE TITLE
Otimização - retirar PSO / Inclusão de mapeamento

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#137]
- Dada a necessidade de incluir a reconciliação de dados, sugere-se retirar o algorítimo de PSO, e substituí-lo por métodos disponíveis nas bibliotecas de otimização.
- Incluir método para mapear a função objetivo.

**Comment by regianesousa** [comment]
Início: 
* métodos que não possuem restrição.
* métodos que não dependem de derivada (jacobiana e hessiana)
* testar métodos que dependem de derivada com opção none

Importante: documentação - rever sistematicamente pois  PSO após o commit c2ce3ec540904de6da9a035a0ecb1a07705249b9  foi retirado

**Comment by regianesousa** [comment]
Atividades 22/02/2019

Metódos implementados : 
- Nelder - Mead;
- Powell;
- BFGS;
- L-BFGS-B;
- CG;

Trabalhar condição inicial, observar resultados.

**Comment by ddss** [comment]
* Documentação do método otimização faz referência a opções, que não são utilizadas no minimize.
