### ISSUE TITLE
gerarEntradas: nova forma de entrar com variáveis

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#139]
Inclusão de método para adicionar dados experimentais na forma de listas.
dados da primeira variável dependente:
Estime.x.add([1,2,3])
dados da segunda variável dependente:
Estime.x.add([4,5,6])
dados da primeira variável independente:
Estime.y.add([0.1,0.2,0.5])

**Comment by regianesousa** [comment]
Feito no commit : e7e1979df47013c21363fbfea453ccbd5632c842
