### ISSUE TITLE
Gráfico de predição com incerteza tem legenda invertida

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#140]
Legenda invertida.

**Comment by ddss** [comment]
Problema na linha 2294:
Fig.set_legenda(['calculado', 'predicao' if self.__flag.info['dadospredicao'] else 'estimacao'],
                        fontsize=16, loc='best')

inverter as posições de calculado e do if

Alterar predição para "dados para predição" e "estimação" para "dados para estimação"

**Comment by regianesousa** [comment]
Feito no commit 3ad93f8ba6adfde55d1870c9af697531b13ba364;
Pendente verificação do gráfico para confirmar correção.
