### ISSUE TITLE
Nomenclatura de grandeza

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#145]
Sugestão de nova nomenclatura 

_SETestimacao -> _SETdadosestimacao
_SETpredicao -> _SETdadosvalidacao
_SETcalculado -> não alterar

Verificar no livro "Análise de dados experimentais I" qual a nomenclatura usada pelo autor

**Comment by ddss** [comment]
@ffmatos concorda?

**Comment by regianesousa** [comment]
Usar nomeclatura sugerida.

**Comment by regianesousa** [comment]
Feito no commit : a318805d1d46323b8f076cd71e8d2dcd649afe9c
