### ISSUE TITLE
Pesquisa sobre usabilidade

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#146]
Pesquisar sobre critérios de avaliação de usabilidade de softwares

**Comment by regianesousa** [comment]
Pesquisa em andamento. 
Sugestões até o momento sobre usabilidade : revisar mensagens de erro, para que fiquem mais claras possíveis, dando clareza ao usuário sobre o erro ocorrido e possível causa.
Feedback sobre o que está acontecendo e sempre que possível como está acontecendo, assim como clareza no passo a passo necessário para execução.
Revisão e melhorias na documentação.

**Comment by ddss** [comment]
Adicione as referências do material consultado (para registro).
