### ISSUE TITLE
Criação de estudos de caso direcionado

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#147]
Implementar estudos de caso de forma guiada/documentada/comentada

Modelos de materiais de referência

**Comment by regianesousa** [comment]
Separar o arquivo testandoEntrada em 3 arquivos distintos, cada um com seu exemplo.

**Comment by regianesousa** [comment]
Ao validar encontrei as seguintes diferenças:

Ponto ótimo (versão atual) : [ 3.05877801  0.10157204  5.04011036  0.4317998 ]
Ponto ótimo (versão anterior) : [3.078495229936609, 0.10246459480678217, 5.041951551834654, 0.43170212293567145]

Os valores são próximos, mais são diferentes. Neste caso é um problema?

**Comment by ddss** [comment]
> Ao validar encontrei as seguintes diferenças:
> 
> Ponto ótimo (versão atual) : [ 3.05877801 0.10157204 5.04011036 0.4317998 ]
> Ponto ótimo (versão anterior) : [3.078495229936609, 0.10246459480678217, 5.041951551834654, 0.43170212293567145]
> 
> Os valores são próximos, mais são diferentes. Neste caso é um problema?

Verifique o valor da função objetivo no ponto ótimo. Qual é o menor? 
Execute também outro algoritmo de otimização (Powell ou Nelder-Mead)

**Comment by regianesousa** [comment]
A menor é da versão antiga, porém utilizando o algoritmo Nelder-Mead, os valores ficam mais próximo.

**Versão Anterior**
FOotimo: 30.1550194699
**Powell**
FOotimo: 30.1602298888
**Nelder-Mead**
FOotimo: 30.1550195173 
Ponto ótimo: [ 3.07845968  0.1024629   5.04192423  0.43170282]

**Comment by ddss** [comment]
Veja que é um resultado do algoritmo de otimização escolhido. Isto pode ser melhorado, alterando algumas das opções, como a tolerância do algoritmo.

**Comment by ddss** [comment]
* Colocar um breve sumário sobre aquilo que cada exemplo trata.
* verificar use('Agg')
* Corrigir ->  A plataforma MT_PEU necessita da incerteza dos dados experimentais, e quando está informação não é disponibilizada, o programa assume valor 1 para todos os dados (ux1, ux2, uy1):
* Simlificar: Otimização será realizada utilizando o algoritmo escolhido pelo usuário (disponiveis: Nelder-Mead, Powell, BFGS, L-BFGS-B, CG),
caso não seja escolhido (como no exemplo abaixo), o algoritmo a ser utilizado por padrão a otimização será realizada utilizando o Nelder-Mead,
com estimativa inicial em [0,5 , 25000,00], para k0 e E respectivamente. Como não foi alterado, o algoritmo utilizado
na otimização será o Nelder-Mead.
* Substituir etapas = ['otimizacao', 'grandezas-entrada', 'predicao', 'grandezas-calculadas', 'analiseResiduos', 'regiaoAbrangencia'] em estime.graficos(etapas)
* Exemplo 3 -> detalhamento das explicações, inclusive do fluxo
