### ISSUE TITLE
Validar matriz singular nas entradas

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#16]

**Comment by ddss** [comment]
Essa matriz se refere à matriz de variãncia e covariãncia dos dados experimentais e de validação.
Muito provavelmente, este teste deve estar em Grandeza

**Comment by ddss** [comment]
Validar de y e x estão vindo com incerteza ZERO.

Impedir!

**Comment by ddss** [comment]
Contemplado no commit b3d3343a1fc5d88c7facf8e1666af0c7b51a2849
