### ISSUE TITLE
[GETFOotimo] Avaliar exclusão

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#162]
As rotinas padrão de otimização do Python que estamos utilizando já retornan o ponto ótimo da função objetivo. Avaliar se este método pode ser excluído, incluindo a variável self.FOotimo, pois
self.Otimizacao.fun já contém esta mesma informação.

**Comment by Matheus2301** [comment]
Professor, boa tarde. Em resumo, nesse caso devo substituir self.Otimizacao.fun por self.FOotimo no arquivo MT-PEU.py e verificar se obtenho os mesmos resultados, no caso, o ponto ótimo, na execução dos exemplos?

**Comment by ddss** [comment]
Não. O contrário.

self.Otimizacao.fun já é calculado pelo minimize. O método self.FOotimo reavalia o valor - portanto, self.FOotimo não é necessário.

**Comment by Matheus2301** [comment]
Professor, analisando o código do MT-PEU.py, tive a impressão que a retirada do self.FOotimo comprometeria a execução dos exemplos, pois a retirada de self.FOotimo na obtenção do ponto ótimo da função, trouxe implicações na estimativa de incertezas e também no que envolvia a hessiana. Poderia me dar um dica de como extrair de self.Otimizacao (minimize) a mesma informação que self.FOotimiza me fornece?

**Comment by ddss** [comment]
> Veja que self.Otimizacao.fun deve retornar a mesma informação - o ponto ótimo da função objetivo. Consulte a documentação do método minimize e verifique.

<sub>[View in Slack](https://minhaequipe-workspace.slack.com/archives/GFYBVEFN0/p1564253774000100)</sub>

**Comment by Matheus2301** [comment]
Já havia olhado, mas vou revê-lo. Obrigado!

**Comment by Matheus2301** [comment]
Boa tarde, professor! Eu consegui! Fiz a exclusão GETFOotimo (self.FOotimo), linha 86, 198-200, 1086-1098 e 1177-1182 no MT-PEU.py e deu certo! No entanto o Exemplo2.py foi o único que não rodou. Em relação aos exemplos que rodaram, houve apenas uma alteração bem pequena nos gráficos de Região/Verossimilhança. No mais, tudo ok.

Mensagem de erro apresentada no exemplo2.

C:\Users\User\Anaconda3\python.exe C:/Users/User/Desktop/MT_PEU-Teste2/Exemplo_2.py
Traceback (most recent call last):
  File "C:/Users/User/Desktop/MT_PEU-Teste2/Exemplo_2.py", line 151, in <module>
    Estime.incertezaParametros(delta=1e-5,metodoIncerteza='2InvHessiana',preencherregiao=True)
  File "C:\Users\User\Desktop\MT_PEU-Teste2\MT_PEU.py", line 1273, in incertezaParametros
    self.Hessiana   = self.__Hessiana_FO_Param(self._deltaHessiana)
  File "C:\Users\User\Desktop\MT_PEU-Teste2\MT_PEU.py", line 1475, in __Hessiana_FO_Param
    FO_otimo = self.FOotimo
AttributeError: 'EstimacaoNaoLinear' object has no attribute 'FOotimo'

Process finished with exit code 1

**Comment by ddss** [comment]
> observe que o erro ocorreu devido às mudança. você precisa correr todo o código do MT_PEU e avaliar onde a propriedade self.FOotimo estava em uso. Veja o final da mensagem de erro.
<sub>[View in Slack](https://minhaequipe-workspace.slack.com/archives/GFYBVEFN0/p1564339995000100)</sub>

**Comment by Matheus2301** [comment]
Certo, vou verificar! Obrigado!

**Comment by tarciso19** [comment]
Resolvida na issue #156 

N° do commit: 6f179bae2093f2e575346d0ecff24f6103a549c8
