### ISSUE TITLE
Dividir a rotina plot_cov_ellip em duas

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#164]
Dividir a rotina plot_cov_ellip em duas:

* uma para gerar a ellipse para o método "Grafico"

* outro para enviar as coordenadas dos pontos extremos da elipse.

Objetivo: evitar criação de eixo matplotlib desnecessariamente

**Comment by Matheus2301** [comment]
Sugestão: em **subrotinas**, trocar o nome de plot_cov_ellipse para eval_cov_ellipse, pois todas as referências a gráficos neste def são excluídos. Bem como as importações referentes aos gráficos.
As variáveis pos, width, height, angle, coordenadas_x, coordenadas_y -> devem ser incluídas em um único "return" (retire o IF).


Para a classe Graficos - no método ellipe_covariancia, excluir todo o código que está repetido em subrotinas -> plot_cov_ellipse (no futuro, eval_cov_ellipse). Basicamente, serão mantidos as plotagens, somente.

**Comment by tarciso19** [comment]
Resolvida

N° do commit: fc846565cd2915eeb99e79b65c1ebc984d95ede9
