### ISSUE TITLE
Correção de gráficos

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#17]
Corrigir gráfico que está "ligando" os pontos.

![calculado_y_funcao_de_t_com_incerteza](https://cloud.githubusercontent.com/assets/7258884/7822056/5bc48f2e-03c9-11e5-9d5d-b79d814501fc.png)

**Comment by AndersonGI** [comment]
Ao verificar os gráficos, não encontrei esta anormalidade.

**Comment by ddss** [comment]
O gráfico continua errado. Veja os gráficos de Grandeza!

Exemplo:
experimental_fl0_y_funcao_t_com_incerteza.png

**Comment by AndersonGI** [comment]
Estes gráficos não estão em Grandeza e sim em MT_PEU, eu não consegui resolver.

**Comment by AndersonGI** [comment]
Parece que é um bug interno do errobar, encontrei isso:
http://stackoverflow.com/questions/18498742/how-do-you-make-an-errorbar-plot-in-matplotlib-using-linestyle-none-in-rcparams

https://github.com/matplotlib/matplotlib/issues/2366

tentei estas alternativas, porém nenhuma funcionou

**Comment by ddss** [comment]
segundo eles, isso foi resolvido em versões mais atuais do matplotlib. Você tentou atualizar a sua biblioteca?

**Comment by ddss** [comment]
Se você usa a distribuição anaconda é mais fácil...

Se for no pythonxy baixa no site do matplotlib.

**Comment by AndersonGI** [comment]
Daniel, atualizei o anaconda e fiz as mudanças e nada, vem cá essa linha não é por causa desse "diagonal" que você plota?

**Comment by AndersonGI** [comment]
![calculado_fl0_y1_funcao_x1_com_incerteza](https://cloud.githubusercontent.com/assets/9400376/8815785/3e5f2e74-2ff4-11e5-8813-09dba8349a35.png)

Veja como ficou.

**Comment by ddss** [comment]
Eu crio a "diagonal"  nos gráficos de y calculado por y experimental.

Acredito que este erro é porque o ``errorbar'' liga os pontos mesmo.

**Comment by AndersonGI** [comment]
Reolvi o problema dos graficos, no proximo commit implemento

**Comment by AndersonGI** [comment]
Resolvido no commit 0a8b5af8fd8a367c4c3ce760af18620962d86f88
