### ISSUE TITLE
Validação de símbolos diferenciados por maiúsculo/minúsculo

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#170]
Sugiro que seja inclusa uma validação dos símbolos. Acredito que Grandeza já realizada validação de símbolos - teríamos de adicionar mais uma validação.

A ideia é verificar se os símbolos apenas se diferenciam pelo maiúsculo/minúsculo. Se isso ocorrer, o código pode gerar um erro ou alterar o símbolo (colocando um underline). Podemos pensar.

bug: o motor de cálculo sobrescreve pastas e imagens com símbolos diferenciados por maiúsculo/minúsculo.

**Comment by ddss** [comment]
`python

for sym in simbolos:
   ...:     teste = [sym==sym2.lower() or sym==sym2.upper() for sym2 in simbolos]
   ...:     if sum(teste) != 1:
   ...:         raise TypeError('Os simbolos não podem ser diferenciados por maiúscula e minúscola: Problema em:'+sym) 
`

**Comment by tarciso19** [comment]
Issue fechada no commit bf68a27
