### ISSUE TITLE
Inserir validação para base path

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#19]

**Comment by ffmatos** [comment]
Validar se é string e se é um caminho válido

**Comment by ddss** [comment]
Eu posso até testar se base_path é uma string.

Mas como base_path pode ser um caminho que pode não existir, ainda, não sei se é possível validar.

**Comment by ddss** [comment]
Atendidio pelo commit c7d15fa23221a1b07155dbdb92fe53964b883942
