### ISSUE TITLE
args em otimiza

### ISSUE THREAD

**Issue by AndersonGI** [ddss/MT_PEU#22]
args deve ser definido em __init__, mas isto não está validado!!!

**Comment by AndersonGI** [comment]
Não resolvido.

**Comment by ddss** [comment]
Coloquei atividade para mim.

**Comment by ddss** [comment]
Depois do commit 20f4ed6809d8cbe3d9768bc5582d6f6035f6cfe7 isto não é mais exatamente um erro.

Talvez até seja necessário retornar ao uso de args em otimiza, definindo a variável args_user ai mesmo.

**Comment by ddss** [comment]
Resolvido no commit 00b63ab8f8ac03b39b20e3218f3683c6a6a9d673
