### ISSUE TITLE
Implementar "pcolor" 

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#24]
Implementar gráfico que mostra a matriz de covariância da predição, dos parâmetros com cores, facilitar a visualização

 matplotlib.pyplot.pcolormesh(*args, **kwargs)
 matplotlib.pyplot.pcolor(*args, **kwargs)

https://stackoverflow.com/questions/26101262/fixing-ylabel-location-in-a-colorbar-in-matplotlib

**Comment by ddss** [comment]
Gráfico alocado em Grandezas.Graficos()
- Lembre-se do if -> experimental, validação e parametros

Em EstimacaoNaoLinear.Graficos()-> em Grandezas-calculadas -> adicionar a "chamada" para os gráficos dos parâmetros  que é o pcolor.

**Comment by AndersonGI** [comment]
resolvido no commit  651abf980e33985fbb8e50ca8ef19e41dc658ce5.
