### ISSUE TITLE
colormap do pcolor

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#33]
O colormap do pcolor deve ser simétrico, para evitar interpretações ruins.

Verificar como personalizar o cmap do matplotlib.

**Comment by ddss** [comment]
Incluir opção do MT-PEU para colormap simétrico ou assimétrico.

EstimacaoNaoLinear.Graficos -> Grandeza.Grafico

**Comment by AndersonGI** [comment]
Resolvido no commit: 8eccbe29a32b97c0ab8540612f493369cb24cd4b

**Comment by ddss** [comment]
Ficou legal a possibilidade de podermos definir o nosso colormap.

Poderíamos até colocar uma opção de 2 colormap: um simétrico e outro assimétrico. O que acha?

**Comment by AndersonGI** [comment]
Pode ser, mas depende da aplicação, no caso da correlação o simétrico é ideal, porque tanto em um extremo como no outro vai ser ruim.

**Comment by ddss** [comment]
Me referi aos colormap da correlação mesmo. 

O default seria simétrico mesmo. Entretanto, haveria uma opção deste ser assimétrico. 

Seria apenas mais uma opção para o usuário.

**Comment by AndersonGI** [comment]
Resolvido no commit 0a8b5af8fd8a367c4c3ce760af18620962d86f88
