### ISSUE TITLE
Gráfico pcolor para as grandezas calculadas

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#34]
Incluir pcolor para Grandezas calculadas.

**Comment by AndersonGI** [comment]
Esqueci como faço isso.

**Comment by ddss** [comment]
Observe que você está criando o pcolor para: experimental, validacao e parâmetros. Existe outro tipo de grandeza cujo ID é calculado.

Você precisa adicionar mais um IF para calcular para este tipo. Veja que o atributo será self.calculado.matriz_correlacao

**Comment by AndersonGI** [comment]
Resolvido no commit 0a8b5af8fd8a367c4c3ce760af18620962d86f88
