### ISSUE TITLE
O método labelGraficos deve ser modificado para permitir omissão de unidade

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#35]
* incluir nova entrada, exemplo printunidade, com default True (as chamadas existentes NÃO serão afetadas)
* este método sṍ retornará unidade de houve unidade definida e se essa nova entrada for True

**Comment by AndersonGI** [comment]
Resolvido no commit: 8eccbe29a32b97c0ab8540612f493369cb24cd4b
