### ISSUE TITLE
Títulos de eixo do gráfico de autocorrelação, ordem dos resíduos e probplot / Legendas / Forma

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#36]
* Incluir título de eixo dos gráficos de correlação
* corrigir títulos dos eixos dos gráficos de ordem dos resíduos e probplot
* Legenda do gráfico de resíduo por y -> retirar símbolo
* Gridlines no gráfico de probplot

Relacionado a #35

**Comment by AndersonGI** [comment]
Resolvido no commit : 8eccbe29a32b97c0ab8540612f493369cb24cd4b
