### ISSUE TITLE
Verificar espaçamento de gridlines

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#37]
Preferir mais finas

**Comment by AndersonGI** [comment]
Resolvido no commit 0a8b5af8fd8a367c4c3ce760af18620962d86f88

**Comment by ddss** [comment]
@AndersonGI  Não existe alterações em  gridlines neste commit. 

Acredito que ainda temos gráficos sem gridlines ou com gridlines diferentes.

**Comment by AndersonGI** [comment]
Resolvido no commit 651abf9
