### ISSUE TITLE
Verificar o cálculo de R2 ajustado

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#39]
Verificar se o cálculo de R2 está adequado com aquele descrito por Greene, 2003:
Fórmula
R_a^2= 1-  (n-1)/(n-k-1).(1-R^2) 

Ações:
* Caso seja equivalente: manter como está
* Caso não seja equivalente: incluir mais este R2ajustado (NÃO SUBSTITUIR O EXISTENTE)

**Comment by ddss** [comment]
k - grandezas explicativas? Olhar referência

**Comment by AndersonGI** [comment]
Checado!!
o R^2 ajustado do programa é equivalente
