### ISSUE TITLE
pclor dos parâmetros

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#44]
Verifique a legenda do gráfico pcolor dos parâmetros.

Ele não as está criando corretamente
![correlacao_fl0_parametro_autocorrelacao](https://cloud.githubusercontent.com/assets/7258884/8854341/d0388aa6-3135-11e5-9b63-dd7917ed5199.png)

Deveria ser a, b e SEM nada subscrito.

**Comment by AndersonGI** [comment]
Porquê?

**Comment by ddss** [comment]
Observe que os parâmetros são a e b.
A matriz de correlação é para estes 2 parâmetros, somente. 

No outro caso, quando temos x e y, não temos os símbolos para CADA ponto experimental e então adicionamos aqueles números subscritos. Aqui não precisa.

**Comment by AndersonGI** [comment]
Resolvido no commit 0a8b5af8fd8a367c4c3ce760af18620962d86f88
