### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by AndersonGI** [ddss/MT_PEU#45]
Daniel, pra sincronizar eu tive que  descartar todas as minhas mudanças, nisso tudo que tinha feito foi apagado, no entanto por sorte eu tinha salvo, então copiei o código e colei, no entanto se eu for dá o commit aqui vai sobrescrever nas suas mudanças, então queria que você salvasse aí o que você fez no ultimo commit, para que eu possa dá o commit aqui. 
Me avise quando posso commitar!!

**Comment by ddss** [comment]
Na verdade se você sobrescrever as mudanças vamos ficar em um loop infinito e não resolveremos.
Siga os passos abaixo:
1 - Você  vai fazer uma cópia deste código que fora alterado e vai SINCRONIZAR novamente.
2 - Você vai usar um programa para diferenciar os códigos e identificar onde suas alterações foram feitas
3 - Com isso feito, você vai alterar o código que fora sincronizado e ai dar commit.


Não faz sentido você enviar este commit e sobrescrever o anterior (não usamos controle de versão para isso).
