### ISSUE TITLE
Gráficos de autocorelação

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#49]
- Documentar os gráficos de autocorrelação
- Não salvar os dois gráficos de vez. Colocar como uma opção qual gráfico será salvo.

**Comment by ddss** [comment]
@AndersonGI, lembre-se de solicitar ao usuário qual gráfico será salvo.

**Comment by AndersonGI** [comment]
Visto que os gráficos eram iguais em termos de função, diferenciando apenas em questão de layout, foi  decidido deletar um deles no commit 5dcebbb52185e504c287cbd49ca1370d077470d9
