### ISSUE TITLE
Erro em EstimacaoNaoLinear quando é definido o sup e o inf com uma quantidade maior de parâmetros do que o modelo necessita

### ISSUE THREAD

**Issue by caiqueaf** [ddss/MT_PEU#50]

**Comment by ddss** [comment]
Será corrigido quando o MT-PEU utilizar mais nova versão do PSO.

Será passado a keyword NP para o PSO.

**Comment by ddss** [comment]
Outra opção é que o MT-PEU valide estas entradas

**Comment by ddss** [comment]
Resolvido no commit 00b63ab8f8ac03b39b20e3218f3683c6a6a9d673
