### ISSUE TITLE
Gráficos de autocorrelação como subrotina

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#51]
Avaliar se transformar gráficos de autocorrelação para uma subrotina é vantajoso.

**Comment by AndersonGI** [comment]
@ddss tem dois issues sobre gráficos de correlação, este e o #49 , qual devo solucionar?

**Comment by ddss** [comment]
Os dois.

Observe que o #49 está associado à milestone "Análise de resíduos".

**Comment by AndersonGI** [comment]
Resolvido no commit 83343932be74f9e14631423bc524a6542bac3283.
