### ISSUE TITLE
Gráficos em Grandeza

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#52]
Avaliar melhorias para deixar o código mais enxuto.

Exemplo: transformar os códigos dos diferentes gráficos em subordinas ou métodos.

Associado a #51

**Comment by ddss** [comment]
@AndersonGI  o seu último commit resolve esta issue?

**Comment by AndersonGI** [comment]
Sim, Resolvido no commit 83343932be74f9e14631423bc524a6542bac3283.
