### ISSUE TITLE
Rever a possibilidade de colocar a opção de análise da função objetivo com chi2 para cada modelo separadamente.

### ISSUE THREAD

**Issue by AndersonGI** [ddss/MT_PEU#53]
Fiz a análise separada para os dois modelos, e percebi que o modelo 1 é muito influenciado pelo modelo 2 quando a análise é feita em conjunto.

**Comment by ddss** [comment]
No exemplo de teste, realmente, esta abordagem é mais apropriada.

Entretanto, o teste de chi2 para a função objetivo é ÚNICO.
