### ISSUE TITLE
Região de abrangência vazia

### ISSUE THREAD

**Issue by caiqueaf** [ddss/MT_PEU#54]
Quando as variâncias são negativas, a região de abrangência está vazia!

**Comment by ddss** [comment]
Opções para tratamento:

- Warning em Parâmetros
- Flag para avisar sobre esta condição
- IF no método gráficos para não gerar esta representação

**Comment by ddss** [comment]
Relacionado com as issues #61

**Comment by ddss** [comment]
O MT-PEU não mais permite o programa prossiga caso matrizes de covariância tenham variância negativa ou zero. (Commit b3c22d614c9a2332d4932520ccc82eddc138d108).
