### ISSUE TITLE
Relatórios de parâmetros incluir função objetivo como float

### ISSUE THREAD

**Issue by caiqueaf** [ddss/MT_PEU#55]
Utilizar o valor da função objetivo como float.

- relatório parâmetros

**Comment by ddss** [comment]
Atendido no commit 19acadd34aa7d0746e00a04db7290bc4f9345d86

**Comment by VictorGerin** [comment]
A desvantagem dessa solução e que ele mostrará zero se o valor estiver na ordem de grandeza igual ou menor que 10^-4
