### ISSUE TITLE
Warning do Matplotlib (fmt)

### ISSUE THREAD

**Issue by caiqueaf** [ddss/MT_PEU#56]
C:\Program Files\Anaconda\lib\site-packages\matplotlib\axes\_axes.py:2651: MatplotlibDeprecationWarning: Use of None object as fmt keyword argument to suppress plotting of data values is deprecated since 1.4; use the string "none" instead.
  warnings.warn(msg, mplDeprecation, stacklevel=1)

**Comment by ddss** [comment]
@AndersonGI ... esta aviso surgiu, provavelmente, após a correção do #17, quando nos plots de errorbar foi utilizado o comando fmt = None.

Seguir o que está no Warning.... fmt = "none"

**Comment by AndersonGI** [comment]
@ddss acho que isso depende muito da edição do matplolib instalado no python, porque eu tinha colocado antes " 'none' " aí deu erro no meu, depois coloquei "None" e funcionou certinho.

**Comment by ddss** [comment]
Este aviso informa que fmt = None será descontinuado em novas versões.

Veja o help da função e analise o que ela diz. Para não colocarmos um valor incorreto.

**Comment by ddss** [comment]
@AndersonGI  isto já fora resolvido?
