### ISSUE TITLE
SETParametro (permitir incluir região sem matriz covariância)

### ISSUE THREAD

**Issue by caiqueaf** [ddss/MT_PEU#57]
Por que não poder inserir a região de abrangência sem matriz de covariância?

**Comment by ddss** [comment]
- Deve ser avaliado se o MT-PEU está preparado para a condição na qual haja informações sobre a região, mas não haja sobre a incerteza dos parâmetros.

**Comment by ddss** [comment]
As validações implementadas nos métodos de incertezaParametros e Gráficos permitem que isto seja realizado.

**Comment by ddss** [comment]
Atendido no commit 82610c25e7e2cb49bf2b8d245c3ababa694580c4
