### ISSUE TITLE
Label Graficos

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#6]
O commit 35fdec20cafa32e82e62fc5c9bdd92c6dece90dd (branch master) altera a forma que a classe Grandeza lida com simbolos, nomes e unidades não implementadas.

Antes do referido commit: as variáveis self.nome, self.label_latex, self.unidades, self.simbolos  quando não definidas eram None

Depois do referido commit: as variáveis são uma lista de None

O método de criação de label do gráfico deve suportar esta nova característica.

**Comment by leonln** [comment]
Resolvido no commit d4699f6ed165f2a801a7c7c76c14a756b7bd80ab
