### ISSUE TITLE
Implementar configFolder 

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#64]
Implementar rotinar para padronizar diretório onde são salvas as saídas (gráficos, arquivos de dados e relatórios).

Ex: self.__configfolder         = {self.__etapasdisponiveis[9]:'Graficos'}

**Comment by ddss** [comment]
Atendido no commit c7d15fa23221a1b07155dbdb92fe53964b883942

Utilizado chaves "fixas" no formato de strings. Variável ._configFolder
