### ISSUE TITLE
Duvidas

### ISSUE THREAD

**Issue by AndersonGI** [ddss/MT_PEU#65]
Esta dedução da matriz hessiana está correta, foi revisada? outra coisa, procurei no livro que está citado como referência para o calculo da hessiana e não encontrei nada sobre o assunto (pode ser que eu não tenha procura direito) , esta referência bibliográfica está correta?

**Comment by ddss** [comment]
Sim. Esta dedução da matriz Hessiana foi deduzida.
O que ocorre é que foi encontrado apenas uma fórmula pronta para o elementos da diagonal principal (veja página 265 do livro Gilat e Subramaniam (2008)). Os autores mostram a dedução da fórmula de diferença central com três pontos para a derivada segunda.

Entretanto, para os elementos que não pertencem à diagonal principal, tivemos de deduzir a expressão.

**Comment by AndersonGI** [comment]
ahhh entendi, mas a referência que está lá é: "(Gilat, Amos; MATLAB Com Aplicação em Engenharia, 2a ed, Bookman, 2006.)",  por isso que não achei nada.

**Comment by ddss** [comment]
Entendi. 
Provavelmente nesta edição do livro também deve ter. Você olhou o capítulo de derivadas numéricas?

**Comment by AndersonGI** [comment]
Não tem esse capitulo, tem aplicação ao cálculo numérico mas só fala de EDO e integral numérica, mesmo assim não fala muito sobre teoria só diz como usa no matlab.

**Comment by ddss** [comment]
Veja o livro: Métodos numéricos para engenheiros e cientistas.

Esse, com certeza tem

**Comment by ddss** [comment]
Se for o caso, podemos alterar essa informação no MT
