### ISSUE TITLE
Nome dos gráficos envolvendo os resíduos

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#76]
O nome dos gráficos envolvendo os resíduos não está de acordo com o padrão.
![erronome](https://cloud.githubusercontent.com/assets/7258884/9231278/bf4d1072-40fd-11e5-97da-7f8fc92ad615.png)

**Comment by ddss** [comment]
Duas coisas são notadas:

1. existe um colchete e aspas no começo dos nomes dos gráficos
1. os nomes não seguem os anteriores. Os novos nomes propostos para estes gráficos não trazem melhorias significativas e sugiro fortemente a volta para os valores anteriores.

**Comment by AndersonGI** [comment]
@ddss  Quanto aos nomes vou tentar ajustar ao padrão anterior, e quanto a estrutura sugere que voltemos a forma antiga?

**Comment by ddss** [comment]
Em relação à estrutura atual, ainda não pude avaliar. Por enquanto, vamos manter a que você propôs.

**Comment by AndersonGI** [comment]
resolvidos no commit 7e03075e1e9bbc7276c64a5fddc2fc3bba042798.

**Comment by ddss** [comment]
Como eu reverti o commit 7e03075e1e9bbc7276c64a5fddc2fc3bba042798, esta solução foi revertida também.

Sugestão: faça um commit para resolver esta questão, somente.

**Comment by AndersonGI** [comment]
Resolvido no commit 5dcebbb52185e504c287cbd49ca1370d077470d9.

**Comment by ddss** [comment]
Irei revisar

**Comment by ddss** [comment]
Os nomes de alguns gráficos de **Y** e **X** estão com o nome de todas das grandezas,

exemplo: 

* experimental_fl0_autocorrelacao_acorr_y1_y2 -> Para a autocorrelação de y1
* experimental_fl0_autocorrelacao_acorr_y1_y2 -> Para a autocorrelação de y2

Isto não faz sentido. Porque o gráfico de correlação (assim como outros) é apenas para 1 grandeza

Solução:

1. ou você retira a indicação dos símbolos - e ai nos guiamos pelas pastas
1. ou você coloca apenas o símbolo da grandeza que aquele gráfico se refere.

Particularmente, acredito ser mais interessante retirar a indicação das grandezas e nos guiarmos pelas pastas. @ffmatos alguma sugestão?

A Figura abaixo marca os gráficos afetados:
![captura de tela 2015-08-22 as 13 35 15](https://cloud.githubusercontent.com/assets/7258884/9424869/a8411d74-48d2-11e5-9bf5-183320df7006.png)

**Comment by AndersonGI** [comment]
Resolvido no commit 5d0238f.
