### ISSUE TITLE
gráficos de resíduos em função de x

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#81]
Os gráficos em função de x devem ser plotados.

**Comment by AndersonGI** [comment]
Resolvido no commit     7e03075e1e9bbc7276c64a5fddc2fc3bba042798.

**Comment by ddss** [comment]
Existe um erro na plotagem deste gráfico!

os símbolos de x e y não podem ter o mesmo índice! Faça o teste para um exemplo com mais de um x e apenas um y.

Outra coisa...
self.x.graph não pode ser executado no MT-PEU, porque vai ficar deveras confuso. Afinal, existem dois métodos para plotagem de gráficos.

Vamos conversar.

**Comment by AndersonGI** [comment]
Adicionado no commit 667ea73a86c32e2bdcf23783ed636c700c9c262b.

**Comment by ddss** [comment]
Os graficos estão sendo salvos na pasta errada.

Observe que agora temos gráficos de resíduos de **Y**  ,  então eles devem ficar na pasta do seu respectivo **Y** e não em x. 

![captura de tela 2015-08-22 as 13 26 16](https://cloud.githubusercontent.com/assets/7258884/9424847/baa29afc-48d1-11e5-9153-2585c609ffa5.png)

**Comment by AndersonGI** [comment]
@ddss isso é questionável, porque temos o gráfico dos resíduos em função do Y predito dentro dos Y's, nesse caso acho mais interessante este gráfico ficar nesta pasta, porque fica mais fácil pra nos guiarmos.

**Comment by ddss** [comment]
@AndersonGI observe o seguinte cenário:
- eu quero encontrar o gráfico do resíduo de y1. Eu tenho de olhar na pasta de x? Não é mais fácil ir na pasta do y1?

Observe que a variável de interesse aqui NÃO é o x.

O fato do gráfico de resíduo de y em função de y está na pasta de Y é porque ele é resíduo dessa variável, independente do que eu estou usando na abcissa.

**Comment by AndersonGI** [comment]
Resolvido no commit 5d0238ffb91db537bba0589f8fbc495ceeb4bfbe.
