### ISSUE TITLE
Melhorar estrutura dos métodos de gráficos em Grandeza

### ISSUE THREAD

**Issue by ddss** [ddss/MT_PEU#85]
A estrutura atual está confusa. Tem a rotina Grafico, graph e tipos e cada uma delas com muitas entradas.

**Comment by ddss** [comment]
Sugerido: 

1. excluir o método tipos e incluir os cálculos em "graph"
1. avaliar as entradas do método "graph", se a variável for self. pode não se necessário passar a informação via argumento
1. modificar o nome do método graph para __construtorGraficos

**Comment by AndersonGI** [comment]
veja se o commit 5d0238f, resolve isso.

**Comment by ddss** [comment]
Após o commit mencionado, alguns gráficos estão com pequenos erros:

- gráficos de tendência de variáveis calculadas e experimentais: linha vertical cruzando o zero. Não deveria haver nenhuma linha destacada.
- gráfico de boxplot: não deveria haver linhas de grade. (No máximo, uma linha fina marcando o zero - mas não é comum)

![experimental_fl0_tendencia](https://cloud.githubusercontent.com/assets/7258884/9454229/c0f7e918-4a96-11e5-9f29-fcc61506a179.png)
![calculado_fl0_tendencia](https://cloud.githubusercontent.com/assets/7258884/9454234/cfff1e5e-4a96-11e5-88af-bb9f6de17c8b.png)
![residuo_fl0_boxplot](https://cloud.githubusercontent.com/assets/7258884/9454243/db0de15e-4a96-11e5-904d-804910458710.png)

**Comment by AndersonGI** [comment]
estes são alguns pontos que tenho que discuti com você, por exemplo nos gráfico de tendencia eu usei o tick que você sugeriu, desta forma as vezes os eixos se "extrapolam", então pra referenciar o zero, eu fiz um avline e um ahline nos eixos.
essa questão do boxplot é facilmente resolvida, aliás as duas.

**Comment by ddss** [comment]
É uma solução interessante para este problema

**Comment by ddss** [comment]
Estrutura de código sugerida para os gráficos:
(o exemplo é de um outro trabalho)

```python
fig = figure(figsize=(8, 6))
ax = fig.add_subplot(1,1,1)
ax.get_xaxis().tick_bottom()
ax.get_yaxis().tick_left()
ax.get_yaxis().set_tick_params(direction='out', labelsize=18)
ax.get_xaxis().set_tick_params(direction='out', labelsize=18)
errorbar(tempoEXP, Rexp, marker='.', linestyle='steps-post:', color='b', linewidth=0.5, label=r'$R^{\mathrm{NP}}$')
ax.legend(fontsize=20)
ax.set_ylabel(labely, fontsize=22)
ax.set_xlabel('$t$ / cycles', fontsize=22)
#ax.xaxis.get_major_formatter().set_powerlimits((0, 1))
ax.yaxis.get_major_formatter().set_powerlimits((0, 1))
ax.set_xlim((0,5100))
fig.subplots_adjust(left=0.125, right=0.98, top=0.95, bottom=0.125)
fig.savefig(base+'prediction-summary-mean-comparison-'+tipo+'.png')
close()
```
