### ISSUE TITLE
Substituir objeto Organizador por um método

### ISSUE THREAD

**Issue by VictorGerin** [ddss/MT_PEU#86]
Como a única função da classe Organizador é armazenar variáveis e essas podem ser criadas dinamicamente.

```python
def funcaoQueCriaOObjeto():
    class vazio:
        pass
    objQueRecebeAsVariaveis = vazio()
    objQueRecebeAsVariaveis.AdicionandoUmaVariavel = 'Valor da Variavel'
    return objQueRecebeAsVariaveis
```

Com essa função você terá dentro uma instancia da classe 'vazio' que so serve para receber as variáveis.
Depois para substituir o objeto Organizador basta ao invés de criar uma instancia do Organizador você pode chamar a função acima.

**Comment by ddss** [comment]
Afeta issue #73

**Comment by ddss** [comment]
Usar innerClass (mesma estrutura proposta em #96)

**Comment by ddss** [comment]
Acesso a atributos de Grandeza em Dados (innerclass)

http://www.hitmaroc.net/96223-8314-access-outer-class-inner-class-python.html
