### ISSUE TITLE
Relatórios: Adicionar  quebra de linha para o Windows, não apenas para Linux

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#89]
O arquivo fica completamente desformado quando aberto em um SO diferente do linux

**Comment by ddss** [comment]
@ffmatos você corrigirá isto?

**Comment by ddss** [comment]
Solução: Adicionar \r nas quebras de linha

- Solução paliativa: abre os arquivos no notepad++ ou wordpad

**Comment by ddss** [comment]
Sugestão: criar variável em relatório para determinar o "pulo de linha" (se \r ou \n) a depender do sistema operacional.
(sugestão de @VictorGerin)
