### ISSUE TITLE
Substituição de while True em ThreadExceptionHanding

### ISSUE THREAD

**Issue by VictorGerin** [ddss/MT_PEU#94]
A ThreadExceptionHanding está sendo "parada" usando um loop "while true", o que trás muitos malefícios em desempenho eleva o uso do processador a 100% sem necessidade alguma.

1º solução ao invés de iniciar uma Thread use o metodo Run direto isso fará a "Thread parar" ,Thread entre apas por que assim ele não é uma Thread, e por tanto o código firar parado no run até finalizar e qualquer error será pego pela thread principal

**Comment by VictorGerin** [comment]
aqui @ddss eu disse que tinha aberto

**Comment by ddss** [comment]
podemos usar aqui o que fora sugerido na issue #95 e eliminar este método.
