### ISSUE TITLE
[Fluxo] Modificação de estrutura em __etapasdisponiveis (variáveis)

### ISSUE THREAD

**Issue by VictorGerin** [ddss/MT_PEU#96]
O objetivo da lista __etapasdisponiveis é de ser armazenar as possíveis opções de etapas.

Mas ao invés de usar uma lista pode-se usar várias variáveis no lugar, o motivo é que assim cada variável terá um nome que representa a sua etapa ao invés de um número e assim facilita a leitura do código fonte.

Para que todas essas variáveis não fiquem "soltas" dentro da própria classe do MT_PEU pode-se fazer algo parecido ao que eu propus com a classe Organizador #86.
Assim essas variáveis ficaram dentro de uma instancia de uma classe que tem como objetivo armazenar elas.

**Comment by ddss** [comment]
```python
class Fluxo()

    def __init__(self):
        self.__gerarEntradas = 0

class EstimacaoNaoLinear(Fluxo):

```

**Comment by ddss** [comment]
Definir Fluxo como uma innerclass de EstimacaoNaoLinear

Link: https://stackoverflow.com/questions/719705/what-is-the-purpose-of-pythons-inner-classes

**Comment by ddss** [comment]
-> Início de implementação commit https://github.com/ddss/MT_PEU/commit/b479213ea83030e14836f7c4b537cf05e9a4a45e

Pendências:
- [ ] documentar
- [ ] definir como esta classe irá lidar com as validações de etapas predecessoras
- [ ] corrigir validações atuais para usar a nova estrutura
- [ ] modificar em EstimacaoLinear

**Comment by ddss** [comment]
```python

@property
def IDBank:
    return {0:'gerarEntradas',1:'otimiza'}

@property
def __predecessoraotimiza():
    return ['gerarEntradas']
   
def SET_ID(id):
    teste =  [ getattr(self,atributo) for atributo in self.__predecessora"id"]


```

**Comment by ddss** [comment]
-> O método de validação pode ser excluído. As validações podem ser deslocadas para cada método separadamente. -> Facilitar a leitura do código.
