### ISSUE TITLE
Revisar alterações na classe e função "Relatórios"

### ISSUE THREAD

**Issue by ffmatos** [ddss/MT_PEU#97]
Revisar as alterações e principalmente atualizar documentação

**Comment by ddss** [comment]
Não entendi este issue.

Que alteração? 

Seria melhor dividir este issue em dois : (1) para alterações, (2) para documentação

**Comment by ffmatos** [comment]
Ainda não fiz o commit. Deixei a issue pra que eu esqueça que preciso fazer a revisão e atualizar a documentação.
